require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '11.0'

target 'Constantino_Randy' do
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])

  # pod 'react-native-facebook-login', :path => '../node_modules/react-native-facebook-login'

  pod 'RNAppleAuthentication', :path => '../node_modules/@invertase/react-native-apple-authentication'

  pod 'react-native-get-random-values', :path => '../node_modules/react-native-get-random-values'

  pod 'RNGoogleSignin', :path => '../node_modules/@react-native-google-signin/google-signin'

  pod 'SVProgressHUD'

  # pod 'RNPaypal', :path => '../node_modules/react-native-paypal-lib/ios'

  pod 'react-native-stripe-payments', :path => '../node_modules/react-native-stripe-payments'

  target 'Constantino_RandyTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  use_flipper!
  post_install do |installer|
    flipper_post_install(installer)
  end
end

target 'Constantino_Randy-tvOS' do
  # Pods for Constantino_Randy-tvOS

  target 'Constantino_Randy-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
